### ISSUE TITLE
angstrom-v2013.12 build issue

### ISSUE THREAD

**Issue by Nils-github** [Angstrom-distribution/setup-scripts#48]
Hello all,
After doing:
git clone git://github.com/Angstrom-distribution/setup-scripts.git
Adding to sources/layers.txt: meta-kirkwood,git://github.com/kelvinlawson/meta-kirkwood.git,master,HEAD
Adding to BSPLAYERS list in conf/bblayers.conf: ${TOPDIR}/sources/meta-kirkwood \
cd setup-scripts
MACHINE=netstora ./oebb.sh config netstora
MACHINE=netstora ./oebb.sh bitbake console-image

I get the following BUILD error(werror): 
~/angstrom/setup-scripts/build/tmp-angstrom_v2013_12-eglibc/work/x86_64-linux/binutils-native/2.23.2-r2013.10-4/binutils-linaro-2.23.2-2013.10-4/bfd/opncls.c: In function 'bfd_fopen':
./bfd.h:529:65: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
 #define bfd_set_cacheable(abfd,bool) (((abfd)->cacheable = bool), TRUE)
                                                                 ^
~/angstrom/setup-scripts/build/tmp-angstrom_v2013_12-eglibc/work/x86_64-linux/binutils-native/2.23.2-r2013.10-4/binutils-linaro-2.23.2-2013.10-4/bfd/opncls.c:268:5: note: in expansion of macro 'bfd_set_cacheable'
     bfd_set_cacheable (nbfd, TRUE);
     ^

It looks to me like the patch: ~/angstrom/setup-scripts/sources/openembedded-core/meta/recipes-devtools/binutils/binutils/replace_macros_with_static_inline.patch
is not being applied.

Am i doing something wrong?
Could you give me a hint to fix the compilation?

Thanks,
Nils.

**Comment by Nils-github** [comment]
I started an other build last night on my laptop. (also a x86-64 machine and also running Debian Jessie)
I didn't use the kirkwood -meta this time.
I build for beagleboard this time:
git clone git://github.com/Angstrom-distribution/setup-scripts.git
cd setup-scripts
MACHINE=beagleboard ./oebb.sh config beagleboard
MACHINE=beagleboard bitbake console-image

And got the same problem.

Thanks,
Nils.

**Comment by The-Compiler** [comment]
I can confirm this with `MACHINE="at91sam9rlek" ./oebb.sh bitbake virtual/kernel` too.

It seems there's a related (or the same?) issue in sdcc:

http://sourceforge.net/p/sdcc/mailman/message/32589131/
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=752972

patch (which I didn't try yet):

http://sourceforge.net/p/sdcc/mailman/attachment/8220492.L4Sj0IM0Ds%40hekla/2/

**Comment by koenkooi** [comment]
The binutils in the meta-linaro recipe lacked 2 patches to fix when building with gcc 4.9. Luckily it's my dayjob to maintain meta-linaro, so I've pushed 2 patches that should fix the issues you're seeing: https://git.linaro.org/openembedded/meta-linaro.git/shortlog/refs/heads/dora

An './oebb.sh update' should drag those in automatically.

**Comment by The-Compiler** [comment]
Great, thank you!
