### ISSUE TITLE
angstrom-v2014.06 build error

### ISSUE THREAD

**Issue by Nils-github** [Angstrom-distribution/setup-scripts#49]
Hello all,
Building Angstrom-2014.06 with meta-linaro daisy is broken due to a missing file.
The following error is in the log:
```
ERROR: Function failed: Fetcher failure for URL: 'http://cbuild.validation.linaro.org/snapshots/eglibc-linaro-2.19-2014.04.tar.bz2'. Unable to fetch URL from any source.
```
The following patch fixes the build:
```
--- meta-linaro/meta-linaro-toolchain/recipes-core/eglibc/eglibc_linaro-2.19.bb
+++ meta-linaro/meta-linaro-toolchain/recipes-core/eglibc/eglibc_linaro-2.19.bb
@@ -6,7 +6,7 @@
 RELEASE = "20${MMYY}"
 PR = "r${RELEASE}"
 
-SRC_URI = "http://cbuild.validation.linaro.org/snapshots/eglibc-${PV}-${RELEASE}.tar.bz2 \
+SRC_URI = "https://snapshots.linaro.org/openembedded/sources/eglibc-${PV}-${RELEASE}.tar.bz2 \
            file://eglibc-svn-arm-lowlevellock-include-tls.patch \
            file://IO-acquire-lock-fix.patch \
            file://mips-rld-map-check.patch \
```
Thanks, Nils.

**Comment by koenkooi** [comment]
That bug needs to be filed with the meta-linaro maintainers.

**Comment by Nils-github** [comment]
That`s what i did. ;)
http://layers.openembedded.org/layerindex/branch/master/layer/meta-linaro/   states:
Mantainer: Koen Kooi

I searched the web but i couldn`t find a meta-linaro bugtracker.
http://www.openembedded.org/wiki/Bug_tracking  states:
Bugs in OpenEmbedded-Core layer should be reported using the Yocto Project bugzilla; other layers may have their own bug tracking mechanisms - see the README in the specific layer.

But unfortunately there is no mentioning of a bugtracker in the meta-linaro readme!
