### ISSUE TITLE
libpng-native build error on build 2014.12

### ISSUE THREAD

**Issue by CISAsystems** [Angstrom-distribution/setup-scripts#50]
I can not build libpng-native because it is configured with the option "--enable-arm-neon=on" from the recipe line:

EXTRA_OECONF_append = " ${@bb.utils.contains("TUNE_FEATURES", "neon", "--enable-arm-neon=on", "--enable-arm-neon=off" ,d)}"

I guess that TUNE_FEATURES has neon on it but for native building it should not.
how can I change it ?

Thanks.

**Comment by koenkooi** [comment]
Should be fixed with https://github.com/Angstrom-distribution/meta-angstrom/commit/6fc16169bf744c01e241bda1f7cd70aebfb5932e
