### ISSUE TITLE
Error compiling for Beaglebone Black.

### ISSUE THREAD

**Issue by joeloliveira** [Angstrom-distribution/setup-scripts#52]
Hello, I'm trying to compile a version for BEAGLEBONE black and I'm getting an error:

Setting: 7 Debian / Ubuntu 14.10

git clone https://github.com/Angstrom-distribution/setup-scripts
MACHINE = BEAGLEBONE ./oebb.sh config BEAGLEBONE
MACHINE = BEAGLEBONE ./oebb.sh update

MACHINE = BEAGLEBONE ./oebb.sh bitbake virtual / kernel
In this command I get:
NOTE: Error during finalize of /home/joel/dev/angstrom/setup-scripts/sources/meta-linaro/meta-linaro/recipes-kernel/linux/linux-linaro-stable-vexpress_git.bb
ERROR: ExpansionError During parsing /home/joel/dev/angstrom/setup-scripts/sources/meta-linaro/meta-linaro/recipes-kernel/linux/linux-linaro-stable-vexpress_git.bb: Failure expanding variable S: ExpansionError: Failure expanding variable SRCPV, expression was $ {@ bb.fetch2.get_srcrev (d)} Which triggered exception FetchError: Fetcher failure is URL: git: //git.linaro.org/kernel/linux -linaro-stable.git; protocol = http; branch = lsk '. The command git ls-remote http://git.linaro.org/kernel/linux-linaro-stable.git refs / heads / lsk refs / tags / lsk casette empty output unexpectedly

Someone has been there?

Thank you.

**Comment by bmagnusen** [comment]
I'm getting essentially the same error building under Ubuntu 14.04:

ERROR: ExpansionError during parsing /home/brianm/external_projects/angstrom/sources/meta-linaro/meta-linaro/recipes-kernel/linux/linux-linaro-stable-vexpress_git.bb: Failure expanding variable S: ExpansionError: Failure expanding variable SRCPV, expression was ${@bb.fetch2.get_srcrev(d)} which triggered exception FetchError: Fetcher failure for URL: 'git://git.linaro.org/kernel/linux-linaro-stable.git;protocol=http;branch=lsk'. The command git ls-remote http://git.linaro.org/kernel/linux-linaro-stable.git refs/heads/lsk refs/tags/lsk gave empty output unexpectedly

I was building successfully a few days ago, then about two or three days ago this problem just cropped up without any changes on my end. Maybe a repository tag got removed or something similar?

After some web searching it seemed that AUTOREV was somehow causing the problem, so in meta-linaro/recipes-kernel/linux/linaro-kernel.inc I replaced
SRCREV = "${AUTOREV}"
with
SRCREV = "b7a37b8b4f219e8b39223157ac311f9e3dc384ec"

That got me building again. I'm guessing there's a better long-term solution, but for now I'm moving on and hoping some light will be shed by someone more astute in these matters than myself.

**Comment by joeloliveira** [comment]
Awesome,
It worked.
Thank bmagnusen.

**Comment by mrkozmic** [comment]
I had the same problem on CentOs 6.6 
I fixed by changing branch from lsk to linux-linaro-lsk in linux-linaro-stable-vexpress_git.bb
SRC_URI = "git://git.linaro.org/kernel/linux-linaro-stable.git;protocol=http;branch=linux-linaro-lsk"

Not sure if this is the right thing to do, but the build moved on. 
(still building...)

**Comment by bmagnusen** [comment]
Looks like it's been fixed in meta-linaro, apparently as of commit 01c40caf03beba8730aeef8726577cd6fb31bedf on 5/1/15. I backed out my previous workaround and everything builds fine now.

Here's what the commit message says:
"linux-linaro-stable-vexpress: lock down SRCREV

AUTOREV in a release branch is insane, so lock it down."
