### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by quikegon** [Angstrom-distribution/setup-scripts#57]
Hi,

While executing "MACHINE=beagleboard ./oebb.sh config beagleboard", following the tutorial, this message is shown:

"env: gawk: No such file or directory"

I have cloned correctly, and I am at the directory "setup-scripts".

Thanks

**Comment by koenkooi** [comment]
You need to install the GNU awk package on your buildhost, e.g. 'apt-get install gawk', 'dnf install gawk' or similar.

**Comment by quikegon** [comment]
Thanks for answer so quickly. But there must be some problem about initial configuration. When I run "apt-get install gawk", the process starts, but it gets interrupted with a "E: Unable to locate the package gawk".

Sorry, I am noob hehe. Maybe network or repositories are not properly configurated?
