### ISSUE TITLE
Kernel panic when booting Angstrom image on imx28evk board

### ISSUE THREAD

**Issue by sonuabraham** [Angstrom-distribution/setup-scripts#63]
Hi,
I am trying to build and run Angstrom image on imx28evk board . I get the following kernel panic on boot . Kindly look into the issue. 

[    9.487716] UBIFS (ubi0:0): UBIFS: mounted UBI device 0, volume 0, name "filesystem", R/O mode
[    9.496588] UBIFS (ubi0:0): LEB size: 126976 bytes (124 KiB), min./max. I/O unit sizes: 2048 bytes/2048 bytes
[    9.506682] UBIFS (ubi0:0): FS size: 236302336 bytes (225 MiB, 1861 LEBs), journal size 9023488 bytes (8 MiB, 72 LEBs)
[    9.517600] UBIFS (ubi0:0): reserved for root: 0 bytes (0 KiB)
[    9.523667] UBIFS (ubi0:0): media format: w4/r0 (latest is w4/r0), UUID 1E931B3C-5F0D-4F1E-B289-76950FFCF30B, small LPT model
[    9.546773] VFS: Mounted root (ubifs filesystem) readonly on device 0:13.
[    9.564543] devtmpfs: mounted
[    9.570181] Freeing unused kernel memory: 296K (c0836000 - c0880000)
[    9.576590] This architecture does not have kernel memory protection.
[   10.736655] systemd[1]: System time before build time, advancing clock.
Mounting cgroup to /sys/fs/cgroup/blkio of type cgroup with options blkio.
Mounting cgroup to /sys/fs/cgroup/devices of type cgroup with options devices.
Mounting cgroup to /sys/fs/cgroup/freezer of type cgroup with options freezer.
Mounting cgroup to /sys/fs/cgroup/pids of type cgroup with options pids.
Mounting cgroup to /sys/fs/cgroup/debug of type cgroup with options debug.
Mounting cgroup to /sys/fs/cgroup/cpu,cpuacct of type cgroup with options cpu,cpuacct.
Mounting cgroup to /sys/fs/cgroup/perf_event of type cgroup with options perf_event.
Mounting cgroup to /sys/fs/cgroup/memory of type cgroup with options memory.
Mounting cgroup to /sys/fs/cgroup/cpuset of type cgroup with options cpuset.
systemd 230 running in system mode. (+PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP -LIBCRYPTSETUP -GCRYPT -GNUTLS +ACL -XZ +LZ4 -SECCOMP +BLKID -ELFUTILS +KMOD +IDN)
No virtualization found in DMI
No virtualization found in CPUID
Virtualization XEN not found, /proc/xen/capabilities does not exist
No virtualization found in /proc/device-tree/*
No virtualization found in /proc/cpuinfo.
This platform does not support /proc/sysinfo
Found VM virtualization none
Detected architecture arm.

Welcome to The Ångström Distribution v2016.12!

Set hostname to <imx28evk>.
Initializing machine ID from random generator.
Installed transient /etc/machine-id file.
[   12.502389] Kernel panic - not syncing: Attempted to kill init! exitcode=0x0000008b
[   12.502389] 
[   12.511603] CPU: 0 PID: 1 Comm: systemd Not tainted 4.8.17-fslc+g35ef795 #1
[   12.518592] Hardware name: Freescale MXS (Device Tree)
[   12.523819] [<c000fba4>] (unwind_backtrace) from [<c000dbe8>] (show_stack+0x10/0x14)
[   12.531638] [<c000dbe8>] (show_stack) from [<c00d0c1c>] (panic+0xbc/0x23c)
[   12.538588] [<c00d0c1c>] (panic) from [<c001bfd8>] (do_exit+0xa30/0xa7c)
[   12.545347] [<c001bfd8>] (do_exit) from [<c001c08c>] (do_group_exit+0x38/0xbc)
[   12.552634] [<c001c08c>] (do_group_exit) from [<c0027cb8>] (get_signal+0x1ec/0x890)
[   12.560342] [<c0027cb8>] (get_signal) from [<c000d098>] (do_signal+0xb4/0x44c)
[   12.567615] [<c000d098>] (do_signal) from [<c000d600>] (do_work_pending+0xc0/0xd8)
[   12.575231] [<c000d600>] (do_work_pending) from [<c000a288>] (slow_work_pending+0xc/0x20)
[   12.583506] ---[ end Kernel panic - not syncing: Attempted to kill init! exitcode=0x0000008b
[   12.583506] 

Thanks in advance ...
Sonu Abraham

**Comment by koenkooi** [comment]
Kernel panics are caused by your BSP vendor, please file a bug there.
